2017-06-02 14:13:17,648 - INFO - [Elapsed time: 0.00] Would you like to set the redmine api key? (y/n)
2017-06-02 14:13:19,416 - INFO - [Elapsed time: 1.77] Checking for extraction requests...
2017-06-02 14:13:19,612 - INFO - [Elapsed time: 1.96] Found 1 issues...
2017-06-02 14:13:19,676 - INFO - [Elapsed time: 2.03] Found extraction to run. Subject: Retrieve. ID: 8902
2017-06-02 14:13:19,677 - INFO - [Elapsed time: 2.03] Adding to responded to
2017-06-02 14:13:19,677 - INFO - [Elapsed time: 2.03] 
Retrieving files...
2017-06-02 14:13:20,233 - INFO - [Elapsed time: 2.59] [Warning] run.py had a problem, continuing redmine api anyways.
2017-06-02 14:13:20,234 - INFO - [Elapsed time: 2.59] [AutoSNVPhyl Error Dump]
Traceback (most recent call last):
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 92, in run_request
    runner = MassExtractor(inputs=inputs)
  File "/home/devon/PycharmProjects/sequence_file_extractor/run.py", line 22, in __init__
    self.outfolder = input['outputfolder']
TypeError: 'builtin_function_or_method' object is not subscriptable

2017-06-02 14:13:20,234 - INFO - [Elapsed time: 2.59] [Error] Dumping...
Traceback (most recent call last):
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 92, in run_request
    runner = MassExtractor(inputs=inputs)
  File "/home/devon/PycharmProjects/sequence_file_extractor/run.py", line 22, in __init__
    self.outfolder = input['outputfolder']
TypeError: 'builtin_function_or_method' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 235, in __init__
    self.main()
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 35, in main
    self.main_loop()
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 118, in main_loop
    self.make_call()
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 137, in make_call
    self.respond_to_issue(found.pop(len(found)-1))
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 173, in respond_to_issue
    self.run_request(inputs)
  File "/home/devon/PycharmProjects/sequence_file_extractor/redmine_listener.py", line 106, in run_request
    get = self.redmine.get_issue_data(inputs['name'])
KeyError: 'name'

